name: Abaplint

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    outputs:
     all: ${{steps.changes.outputs.all}}
    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get changed files
        id: changes
        run: |
          {
            echo 'all<<EOF'
            echo $(git diff --name-only HEAD^)
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: abaplint
        uses: valeriast/actions-abaplint@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGEDFILES: ${{ steps.changes.outputs.all }}
